


export default interface ITransaction {
     _id: string,
     userId: string,
     currency: string,
     amount: number,
     transactionFee: number,
     transactionType: "swap" | "deposit" | "withdrawal" | "transfer" | "buy" | "sell" | "receive",
     exchangeRate: number,
     exchangeCurrency?: string,
     exchangeValue: number,
     status: string,
     involves3rdParty: boolean,
     additionalInfo?: {
          id: number,
          txRef: string,
          orderRef: string,
          flwRef: string,
          redirectUrl: string,
          device_fingerprint: string,
          settlement_token: null,
          cycle: string,
          amount: number,
          charged_amount: number,
          appfee: number,
          merchantfee: number,
          merchantbearsfee: number,
          chargeResponseCode: string,
          raveRef: string,
          chargeResponseMessage: string,
          authModelUsed: string,
          currency: string,
          IP: string,
          narration: string,
          status: string,
          modalauditid: string,
          vbvrespmessage: string,
          authurl: string,
          vbvrespcode: string,
          acctvalrespmsg: string,
          acctvalrespcode: null,
          paymentType: string,
          paymentPlan: null,
          paymentPage: null,
          paymentId: string,
          fraud_status: string,
          charge_type: string,
          is_live: number,
          retry_attempt: null,
          getpaidBatchId: null,
          createdAt: string,
          updatedAt: string,
          deletedAt: null,
          customerId: number,
          AccountId: number,
     },
     txnHash: null,
     orderId: null,
     confirmations: number,
     paymentMode: null,
     walletAddress: null,
     description: string,
     bankName: null,
     bankCode: null,
     accountName: null,
     accountNumber: null,
     isFlagged: boolean,
     actualUtcPaymentDate: null,
     acutalLocalPaymentDate: null,
     reference: string,
     createdAt: string,
     updatedAt: string,
     __v: number,
     id: string,

}